name: Build ISO
on: [push, pull_request]
jobs:
  build_bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v1
      - run: ./build_image.sh -y bullseye
      - run: ./pack_iso.sh -c demo -y output/bullseye-*.gz mac-mini-2018
      - run: ls -l output/
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: bullseye
          path: output/*.iso
  build_bullseye-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v1
      - run: ./build_image.sh -y bullseye-k8s
      - run: ./pack_iso.sh -c demo -y output/bullseye-k8s-*.gz mac-mini-2018
      - run: ls -l output/
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: bullseye-k8s
          path: output/*.iso
  build_proxmox-ve:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v1
      - run: ./build_image.sh -y proxmox-ve
      - run: ./pack_iso.sh -c pve-demo -y output/proxmox-ve-*.gz mac-mini-2018
      - run: ls -l output/
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: proxmox-ve
          path: output/*.iso